### ISSUE TITLE
Users are logged off during a video conference session

### ISSUE THREAD

**Issue by ryannewington** [lithnet/idle-logoff#1]
From: Mike Guyette

Is there a way to potentially modify this to add additional options to allow for a message to pop indicating that they will be logged off? I know this goes against what the initial use was when written, but in my company we have conference rooms, demo rooms, and phone booths all over. The issue is many logon and dont logoff when done. This fixes that issue. However, for people in webex calls that are not giving any mouse or keyboard imput within 30 minutes are having issues with the computer suddenly logging out. There is no warning. For these one off instances I would like to find another way to warn users, but without paid solutions we have come up blank. Thanks!!

**Comment by ryannewington** [comment]
I've added support in this build for actually detecting if a video conference, presentation, media playback, etc is in progress. It will not force the user out if these are in progress anymore.

Feel free to let me know if you don't think this will address the issue. I can look at adding a pop-up notification in, but it will take a bit more time and testing.

**Comment by ryannewington** [comment]
Latest build https://github.com/lithnet/idle-logoff/releases/tag/v1.1.6412

**Comment by Pridhac** [comment]
I'm interested in using this idle-logoff in our Win10 computer labs, but at first glance see two issues. Our lab users may be in a lecture or tutorial, and listening to the academic and allow the machine to be idle, but still be there and have unsaved files open, so ideally, the user would receive a warning about imminent log-off, and would be able to cancel the log-off

1.	Forces log off whether the user wants to be logged off or not. In other words they can't cancel the log off.
2.	It doesn’t give any warning with log off or warning timeout for our students or staff.

What do others think about this use-case?

**Comment by thecstreets** [comment]
I would be interested in a warning message with the ability to cancel as well. We're investigating using idle-logoff for our computers labs and other shared spaces.

**Comment by ryannewington** [comment]
@thecstreets @Pridhac lets move this conversation over to #10 
I've got a beta build available there if you'd like to test.

**Comment by Pridhac** [comment]
Thanks Ryan. We will test and come back to you, Thanks again
