### ISSUE TITLE
usage for specific users only

### ISSUE THREAD

**Issue by vip32** [lithnet/idle-logoff#11]
hi @ryannewington ,
does the program itself need to be run for it to logout inactive users? or does it change a windows policy which takes care of this?

i'm trying to use the inactivity logout for **specific** users, maybe if i run the program only for these users it can work. if it's a windows policy it's probably machine-wide.

how would you handle such a scenario?

**Comment by ryannewington** [comment]
@vip32 the group policy provides the settings for the application only. The application still needs to be installed the machine. If the application is installed, but no group policy is applied, it won't do anything.

If you want to target specific users, then apply the GPO to those users only.

**Comment by ryannewington** [comment]
@vip32 I'll close this issue off. If you need any additional assistance, feel free to reopen it.
