### ISSUE TITLE
Lithnet to install on all PC's?

### ISSUE THREAD

**Issue by wajeehr** [lithnet/idle-logoff#12]
Dear Sir,

I have copied admx and adml to a central store in my windows 2012 R2 server. I need to know the application itself need to be installed on every PC where we want to have idle log off? OR by just copying admx and adml to central store will help us to impose the idle log off for users in our environment?

If software needs to be installed, it has to be done by GPO offcourse, So what is the most appropriate way at user login ? OR at PC reboot, please guide

Apprecaite all your help in this regard

**Comment by ryannewington** [comment]
Hi @wajeehr 

You need to install the MSI on every machine you want to enforce logoff. The ADMX files are only for configuring the policy settings. So each machine must have the MSI installed, and either the user or computer level policy applied to it.

The MSI is a per-machine installer, so don't install it per-user. Once per machine is fine.

**Comment by wajeehr** [comment]
Dear Sir,

Thank-you very much for your reply.

Last point I didn't get

"The MSI is a per-machine installer, so don't install it per-user. Once per machine is fine."

Can you please elaborate.

Regards,
Wajeeh


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ryannewington** [comment]
You mentioned if you should install it via GPO at user login. My answer is no, install it per machine, which will install before user login or on reboot. Alternatively, use a software deployment tool such as SCCM to deploy the MSI to your workstations.

**Comment by wajeehr** [comment]
Thank-you very much, it is clear to me now.

Again thanks,

Regards,
Wajeeh

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
