### ISSUE TITLE
UAC on workstations

### ISSUE THREAD

**Issue by wajeehr** [lithnet/idle-logoff#13]
Dear Support,

I have created two GPO, one for installing idle logoff and other to define setting (time) for idle logoff, however I observed software is not getting installed, so the next GPO for checking time will not work.

manually when I tried to install software msi, I got a pop up to enter admin credentials, once entered, it installed and then after idle time defined in GPO PC was logged off.

I checked my UAC settings are at stage two from top. So is it getting failed due to UAC ? OR what needs to be checked? Please note our users in environment or not admin's on their PC's

Regards,

**Comment by ryannewington** [comment]
The UAC prompt you are seeing when running the app is only because you are opening the app in settings editing mode. Using the app normally in idle logoff mode does not require admin rights. 

You do not need to change your UAC settings. The app needs admin rights to install, but user rights to run.

Ensure your software installation GPO is a machine GPO, not a user GPO. Other than that all I can advise is you need to diagnose the GPO software installation process. Event viewer should provide some information as to why the installation failed.

**Comment by wajeehr** [comment]
Hello, Yes, I created GPO and linked it to OU where I have my user machines and configured settings for software installation in 'computer configuration' section of GPO.

ok, I checked the client event viewer, I can see a warning saying 'Windows failed to apply software installation settings' EVENT ID is 1085, when I click 'Details' I see a ErrorDescription where I have message
' The installation source for this product is not available. Verify that the source exists and that you can access it and DC name shown there is my DC02, while I created and shared the software installation folder on DC01, so if I have two DC's I need to make two folders two shares? 

In share permissions ONLY 'Users' of domain should be given read permission and under security Domain users 'read, write, execute'

**Comment by ryannewington** [comment]
In the GPO, you must specify a UNC path to the installer MSI file. It doesn't matter where it is, as long as all machines can access it and domain computers have read access.

**Comment by wajeehr** [comment]
in the GPO under security filtering, there is ONLY 'authenticated users' which is by default, any thing to modify there?
also when I created the share for this software, under 'permissions' I have removed 'everyone' and added my domain 'users' with 'read' 
OR I keep it to default which was 'EveryONE' with 'read' ?

Appreciate all your time and help. I will again look into it and will reply you with an update.

Regards,

**Comment by ryannewington** [comment]
You need computers to read the share, not users. So your choices are 'authenticated users', 'everyone', or 'domain computers'

**Comment by wajeehr** [comment]
I found that it was a name resolution issue and PC's were unable to resolve FQDN of DC where the shared folder for 'idle-logoff' software is created. Once I fixed the name resolution, I was able to install software from GPO.

My software install GPO is linked to PC's and in 'security filtering' section it is 'authenticated users' and it worked, I checked for two PC's till now, so no need to add 'domain computers' OR needed?

Now once we have this policy GPO in place and software installed on PC's, if the PC reboot again, next time again the installation will run OR it is smart enough to find that software is already there and don't process gpo

**Comment by wajeehr** [comment]
What is the maximum value can be specified for idle time out in minutes?

Thanks,

**Comment by RobinBeismann** [comment]
@wajeehr If the installer exited with a non-error exit code, the software installation group policy will not try to reinstall it, however since this can result in longer startup times, please make sure that you've tested it on some machines before deploying it on all machines.

**Comment by ryannewington** [comment]
@RobinBeismann thanks for helping out here!

@wajeehr did you need any further assistance?

**Comment by wajeehr** [comment]
Hello,

Thanks for asking. I'm ok at the moment. If required I will ask you. 

Kind regards
