### ISSUE TITLE
Error importing administrative templates

### ISSUE THREAD

**Issue by jtebbetts** [lithnet/idle-logoff#16]
Getting the following issue when trying to import the templates into AD. Environment is Server 2012R2 and Server 2016.

Encountered an error while parsing.
DTD is prohibited.

File

\\servername\sysvol\servername\policies\policydefinitions\lithnet.admx, line 7, column 9

**Comment by ryannewington** [comment]
@jtebbetts,

Where did you source the ADMX files from? This error generally indicates they are corrupted in some way. 

Ryan

**Comment by jtebbetts** [comment]
Ryan,

grabbed from this link - retrieved out of the source code zip.

https://github.com/lithnet/idle-logoff/releases/tag/v1.1.6999

**Comment by ryannewington** [comment]
Can you try to install the MSI and copy them out of the local policy store `%SystemRoot%\PolicyDefinitions\Lithnet`

**Comment by ryannewington** [comment]
@jtebbetts did you need any additional assistance with this issue?

**Comment by jtebbetts** [comment]
Ryan

No, actually I was able to get it working with your last email. Thanks!

Jesse

**Comment by ryannewington** [comment]
Awesome! glad you got it working!
