### ISSUE TITLE
Installs to all users individually WIn10 Pro 1903

### ISSUE THREAD

**Issue by wwwaltz1973** [lithnet/idle-logoff#18]
IdleLogOff is asking each user to install and then wants admin credentials. I have not been able to adjust the credential requirements or change the arguments to silent.  How should I handle this?

Thanks

**Comment by ryannewington** [comment]
hey @wwwaltz1973. happy to help. tell me a bit about how you are installing it

**Comment by wwwaltz1973** [comment]
Shared directory on file server. We do not have SCCM or WSUS set up.
  I am using GP to push  the install using Comp Config>Policies>Software Settings> Installation Idle Logoff Utility with assigned deploy
I am using a separate GP using Comp Config> Admin Templates> Lithnet> Idlelogoff to set the parameters.

It deploys fine from the outside but every user is asked to allow or decline the app to make changes. 
I am probably missing something stupid and small but I definitely do not want my users having access to disable the application.

Thank you.

**Comment by ryannewington** [comment]
Is the UAC appearing for installation only or every time the user logs on by the app itself?

If it's the installer, you'll need to assign the application to the computer. When assigned to the computer, it installs at computer start up and runs as local system. When assigned to the user, it runs after user logon, with the user's permissions.

If it's the app itself, have you done anything to cause it to launch in a non standard way? The installer created the autorun keys to make it start at logon with the appropriate switches to activate it in the right mode. If you just run the exe itself without the switches, it will launch in config mode which will trigger a UAC prompt.

**Comment by wwwaltz1973** [comment]
Thank You!  That made me realize where I broke it..

**Comment by ryannewington** [comment]
Your welcome. Feel free to reach out if you have any additional questions.
