### ISSUE TITLE
It does not start if you do not log in

### ISSUE THREAD

**Issue by hquintin** [lithnet/idle-logoff#19]
It does not work if you do not log in
When the device starts and stays in Ctrl + Alt + Sub, the process is not started.
Is there any way to start it without logging in the user?
Tested on Windows 7 x64

**Comment by ryannewington** [comment]
Yep, that's expected. It's a tool to log off idle users. What's the scenario you are trying to support? I may be able to advise alternatives.

**Comment by hquintin** [comment]
Hello,

I want the computers to shut down after 2 hours of inactivity, even if they are not logged in (Ctrl + Alt + Sup).

Thank you!

**Comment by ryannewington** [comment]
You could create a GPO that sets up a scheduled task to shutdown the PC when idle
Something like ->
https://www.windows10forums.com/articles/shutdown-after-pc-has-been-idle.41/
