### ISSUE TITLE
Add support for reboot instead of logoff

### ISSUE THREAD

**Issue by albetorivas** [lithnet/idle-logoff#2]
Hello, as noted in your blog I have set another GPO ( User Configuration/Windows Settings/Scripts/Logoff... running a shutdown -r -t 0 ) in order to reboot the PC each time there is a logoff ( which is working ok ).. but when lithnet application triggers a logoff this I'm talking about, it does nothing. I tried both commands ( shutdown -l ) and ( shutdown -l -f ) but both commands allow this GPO to be triggered ( So no difference found  when using -f parameter).  If you have any other tests or recommendations I can perform would be great. Or I don't if you could add an optional feature in order to logoff (-force) the user + Shutdown the computer  ( only if this feature is selected )

Thanks !
Alberto Rivas

**Comment by ryannewington** [comment]
Hi @albetorivas ,

Try this version with built-in support for performing a reboot instead of a logoff.

[lithnet.idlelogoff.setup.zip](https://github.com/lithnet/idle-logoff/files/1219260/lithnet.idlelogoff.setup.zip)

**Comment by ryannewington** [comment]
Hi @albetorivas,

Try this build and let me know how it goes. I've added support for performing a logoff, reboot, or shutdown at the end of the idle time out.

[lithnet.idlelogoff.setup.msi.zip](https://github.com/lithnet/idle-logoff/files/1219433/lithnet.idlelogoff.setup.msi.zip)

If it works, i'll make a public release

Ryan

**Comment by albetorivas** [comment]
Hi Ryan,
I have tested the new release, and it is working !, I have tested the reboot option.
are those options configurable using the GPO?
Thanks

**Comment by ryannewington** [comment]
@albetorivas yes, you can use gpo. The installer would have dropped the new ADMX files for you to test that with as well.

**Comment by ryannewington** [comment]
@albetorivas production release is here https://github.com/lithnet/idle-logoff/releases/tag/v1.1.6439
