### ISSUE TITLE
GPO roll-out of MSI

### ISSUE THREAD

**Issue by brhunt1958** [lithnet/idle-logoff#20]
I have tried to install the MSI package via a GPO, but it fails ever time I try.  

Do you know if it is possible to do this?  Something additional that I need to do?

Thanks.

Bryan Hunt

**Comment by ryannewington** [comment]
Hi Bryan

Are you pushing it out as a computer wide installation (it can't be installed as a user)

What's the error code you get?

**Comment by brhunt1958** [comment]
Ryan,

Thanks for the reply.

Here are the System event log messages in sequence:

The assignment of application Lithnet Idle Logoff Utility from policy Settings-Logoff Idle User Sessions-Install succeeded.

The install of application Lithnet Idle Logoff Utility from policy Settings-Logoff Idle User Sessions-Install failed.  The error was : %%1612

The removal of the assignment of application Lithnet Idle Logoff Utility from policy Settings-Logoff Idle User Sessions-Install succeeded.

Failed to apply changes to software installation settings.  Software changes could not be applied.  A previous log entry with details should exist.  The error was : %%1612

Windows failed to apply the Software Installation settings. Software Installation settings might have its own log file. Please click on the "More information" link.


[cid:image001.png@01D5D9C9.90643D80]



The GPO is a Computer Configuration.

Thanks.

Bryan Hunt

**Comment by ryannewington** [comment]
Hi Bryan,

``` 
ERROR_INSTALL_SOURCE_ABSENT	1612	The installation source for this product is not available. Verify that the source exists and that you can access it.
```

Either the computer can't access the location where the MSI is located, or the computer doesn't have permission to read that location. You may need to ensure that 'Domain Computers' has read rights to the MSI location.

**Comment by brhunt1958** [comment]
Ryan,

I did some more digging on the issue and found exactly that.  It was a permissions error.

Since the software is installed at boot time and before user log-in, it runs as local system.  I had to give ‘everyone’ read rights to the msi, that cured it.

Thanks for assisting with this.  Looking forward to actually using the program now…

Bryan Hunt
