### ISSUE TITLE
AWS Workspace

### ISSUE THREAD

**Issue by insight2663** [lithnet/idle-logoff#21]
Trying to force workspace to shutdown after 60 mins of inactivity. AWS Workspace are actually windows server 2016 with a win 10 front end. Installed manually to test and set group policy for setting error in event viewer is there were still active sessions and could not shut down. logged off instead. I was the only active session. Any ideas ?

**Comment by ryannewington** [comment]
@insight2663 this is usually because windows did not give the app the appropriate permissions to shutdown the server. Has permission to shutdown the machine been removed from standard users? Were there any errors from idle logoff in the event log?

**Comment by insight2663** [comment]
Thanks , you are correct . It’s working great now . You did great job . Amazon workspace offers some interesting challenges . You solved a big one that saved my company a lot of cost . Thanks again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ryannewington** [comment]
I'm glad you are finding it useful!
