### ISSUE TITLE
Amazon Workspace does not reboot/logoff

### ISSUE THREAD

**Issue by robjpfoster** [lithnet/idle-logoff#23]
Good day,

I've set idle logoff to restart our Amazon Workspaces after 175 min if inactivity using GPO and when closing out the client and checking next day I am still logged on, even with "always on" Workspace.  Is there anything I can be checking?

**Comment by robjpfoster** [comment]
Response from AWS:

Hello,

Thank you for clarifying this, I understand the situation quite clearly now. You are attempting to use a third party program "Idle-Logoff" by Lithnet to accomplish your goals of enforcing reboots or logoffs after inactivity for security reasons.

To begin, I would first like to set the correct expectations that third party software support and GPO configuration falls outside of our Scope of Support [1] [2]. However, I can offer some general guidance on a best effort basis.

I have taken the liberty of reproducing this in my own lab environment by downloading the Idle-Logoff program and attempting to apply the settings as demonstrated in the documentation. Unfortunately, it didn't work as described and I wasn't able to get the application to perform any of the tasks. I then attempted to push the settings via GPO as well, but that also failed. As this is a third party program, I cannot provide more troubleshooting steps than what is available online as I do not know how it works or what would be causing it to not work as expected. I additionally looked through other cases for this program, but couldn't find any similar use cases. I would recommend reaching out to the developers of this program to determine what may cause it to not work correctly.

I have found some other alternatives that you can take advantage of. One such alternative would be to use GP to create a scheduled task on the WorkSpaces to monitor for events:
        PCoIPAgentService Event IDs
                Session End - 89
                Interrupted – 94
These event IDs are generated during the disconnection of the WorkSpaces client. The task can then create an action for this filtered ID and run a logoff.bat file with the code "logoff console", or whatever action you'd like to do such as restart "shutdown /r /t 0". I understand that this may not fit your use case as it only works after the WorkSpaces client is closed, but if this solution is of interest to you, please do let me know as I have an in-depth guide for it. There are also many other ways of completing this goal as I have seen online such as using task scheduler, registry edits, and logon scripts.

I hope you understand the inability to provide further support with this third party program, I do apologize for the inconvenience. As always, let me know if you have any further questions, I will be happy to assist. Thanks.

References:
[1] Shared Responsibility Model - https://aws.amazon.com/compliance/shared-responsibility-model/
[2] Scope of Support - https://aws.amazon.com/premiumsupport/

Your feedback is important to us, please share your experience by rating this response. You will find a link to the AWS Support Center at the end of this correspondence to rate us.

Best regards,

Tanner S.
Amazon Web Services

**Comment by ryannewington** [comment]
@robjpfoster 

When you run the app from the start menu, does it show the correct settings as configured by group policy?

**Comment by robjpfoster** [comment]
Yes everything is correct

Sent from my iPhone

On Jun 9, 2020, at 16:04, Ryan Newington <notifications@github.com> wrote:

﻿

@robjpfoster<https://github.com/robjpfoster>

When you run the app from the start menu, does it show the correct settings as configured by group policy?

**Comment by robjpfoster** [comment]
OS is Windows 10 1909 x64

Sent from my iPhone

On Jun 9, 2020, at 16:04, Ryan Newington <notifications@github.com> wrote:

﻿

@robjpfoster<https://github.com/robjpfoster>

When you run the app from the start menu, does it show the correct settings as configured by group policy?

**Comment by ryannewington** [comment]
When you log on, do you see the lithnet.idlelogoff executable running in task manager under your username?

If so, can you please have a look in the event viewer for events by idlelogoff that may indicate why the logoff process didnt work.

Are you trying to log the user off, restart, or shutdown?

**Comment by ryannewington** [comment]
What is the policy you gave implemented? To reboot after 3 hours?

**Comment by robjpfoster** [comment]
Yes 175 min.  It appeared to work so now I’m trying to isolate when it doesn’t, or maybe it’s resolved.  I will let you know my findings

Sent from my iPhone

On Jun 11, 2020, at 16:23, Ryan Newington <notifications@github.com> wrote:

﻿

What is the policy you gave implemented? To reboot after 3 hours?
