### ISSUE TITLE
.NET unhandled exception when attempting to show warning message

### ISSUE THREAD

**Issue by KTac** [lithnet/idle-logoff#24]
Thank you for the work you've down on this program so far. On paper it looks like the answer to a problem I have. However I have not been able to get it to work. In my situation I need to have a warning message displayed before logging off idle users. However, when the warning message is supposed to fire I get the following .NET unhandled exception:

![image](https://user-images.githubusercontent.com/7475912/91494191-78e8b600-e886-11ea-8998-b8959e9e530e.png)

Here are the details:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
>    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.String.Format(String format, Object arg0)
>    at lithnet.idlelogoff.LogoffWarning.UpdateLabelText()
>    at lithnet.idlelogoff.LogoffWarning.set_LogoffDateTime(DateTime value)
>    at Lithnet.idlelogoff.Program.ShowWarning()
>    at Lithnet.idlelogoff.Program.EventTimer_Tick(Object sender, EventArgs e)
>    at System.Windows.Forms.Timer.OnTick(EventArgs e)
>    at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> lithnet.idlelogoff
>     Assembly Version: 1.1.7478.24869
>     Win32 Version: 1.1.7478.24869
>     CodeBase: file:///C:/Program%20Files%20(x86)/Lithnet/IdleLogoff/Lithnet.IdleLogoff.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4180.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 
> 
> 

If I hit 'Continue' a second and identical unhandled exception box appears. A third one does not appear if I hit 'Continue' again, it just goes away. If I do not touch the unhandled exception window and continue to leave the session idle it will logoff when it is supposed to. It seems the program is still doing what it's supposed do in the background and the unhandled exception only pertains to displaying the warning message.

I could be totally off, but from what I've observed while testing, if the number entered in the "Log off after (minutes)" field is less than the number entered in the "Duration of warning message (seconds)" field, it will result in an unhandled exception when the warning message attempts to fire. Here is a picture for clarity:

![image](https://user-images.githubusercontent.com/7475912/91496029-76d42680-e889-11ea-852f-b7a71bbdcc43.png)

These are some of the values I tested with. A small 'log off after' value so I don't have to wait around too long. In this case I believe after one minute idle the warning should fire and after another minute idle the session should log off. But after one minute idle I get the unhandled exception and after another idle minute it logs off. This would also make the values that I intend to use in production unworkable, which are log off after 30 minutes idle with a 300 second (5 minute) warning.

Further, If I set the values so that the number in the 'log off after' field is greater than the number in the 'duration of warning' field (for example log off after 5 minutes with a 4 second long warning message) then I do not get an unhandled exception. However, I do not get a warning message either. I just get logged off without a warning message ever appearing.

I hope this is helpful and I do hope this gets ironed out so that I can use your program.

**Comment by ryannewington** [comment]
Hey @KTac 

Thanks for reporting this one. The placeholder text must be `{0}` in your warning message. Can you change that and see if it behaves as expected?

I'll need to update the help to make this more discoverable, and probably not unhelpfully crash like it does now.

**Comment by KTac** [comment]
Fantastic! It works beautifully. Now it does just what I need. I'm going to implement this first thing in the morning.

If I may make a suggestion, I plan on having a 30 minute idle timeout with a 5 minute warning which will show a countdown of 300 seconds. It would be nice to be able to show the countdown in mm:ss format if it is greater than 60 seconds. I'm splitting hairs though. I'm very happy with this. Thank you!

**Comment by ryannewington** [comment]
[lithnet.idlelogoff.setup.zip](https://github.com/lithnet/idle-logoff/files/5139969/lithnet.idlelogoff.setup.zip)

That makes sense. Try this build and let me know if it's what you are after. If its all good, I'll update the released version.

**Comment by KTac** [comment]
This is perfect! Thank you so much!

**Comment by KTac** [comment]
I hate to be a bother but test version you provided above has a different checksum and slightly higher version number (1.17545.25524) than the new release you published (1.1.7545.16284). The new release version does not include the change of the countdown to minutes:seconds as stated in the commit it's linked to. The test version above does.

**Comment by ryannewington** [comment]
I haven't released the version I have you to test yet. If you're happy it is working as expected I'll release it

**Comment by KTac** [comment]
I'm sorry, I guess I misunderstood. I saw you released v1.1.7545 yesterday and I thought it looked like it was supposed to the mm:ss countdown change added. Yes, I am very happy with it. It is working exactly as expected. Please release it. Thank you!

**Comment by ryannewington** [comment]
Done https://github.com/lithnet/idle-logoff/releases/tag/v1.1.7548

It's a new version number but the same build as you currently have.
