### ISSUE TITLE
Application does not start in Remote App

### ISSUE THREAD

**Issue by hzo** [lithnet/idle-logoff#25]
The app does not show up as active when users login via Remote App on the server. Only Remote Desktop users get the active app running.

**Comment by ryannewington** [comment]
The app is launched by the shell - explorer.exe. I dont think that remote app sessions launch the shell, therefore the app wouldn't fire off.

You'll need to look for another solution to launch the idle logoff app. Perhaps a batch file?

https://social.technet.microsoft.com/Forums/lync/en-US/2aed355d-29cd-438b-ad97-cd81b4f2cb8d/logon-through-remote-app-2012-r2-won8217t-start-applications-in-8220common-startup8221-map?forum=winserverTS

**Comment by hzo** [comment]
I was able to work around this 

Edited an existing GPO targeting the RDS servers with existing ADMX extension for IdleLogoff
Adjusted the IdleLogoff value via GPO
Computer->Windows Settings -> Scripts -> Startup 
Press "Show Files"
Copied C:\Program Files (x86)\Lithnet\IdleLogoff\Lithnet.IdleLogoff.exe into the SYSVOL\GPO path from "Show Files"
Added Lithnet.IdleLogoff.exe in the startup of GPO
Forced a gpupdate via gpupdate /force /target:computer on all the servers targeted
Launched a Remote App as a user and observed from admin account the user has the EXE in their process list.
