### ISSUE TITLE
Document CLI switches

### ISSUE THREAD

**Issue by hzo** [lithnet/idle-logoff#26]
Can you document the CLI switches in your Wiki?

no switch - Requires Admin Rights, provides GUI options for settings
/start  - make the app run silently based on pre-existing settings or GPO policies.
/help would be useful

**Comment by ryannewington** [comment]
Hi @hzo 

There is only the single command line switch of `/start` which as you pointed out, starts the app in idle logoff mode.

Ryan

**Comment by hzo** [comment]
@ryannewington it would be useful to have that in the Wiki and as output in the executable using /? That's all, you may close this.
