### ISSUE TITLE
Idle-Logoff GPO not working

### ISSUE THREAD

**Issue by rkasenchak** [lithnet/idle-logoff#28]
I created the GPO for my login but it will not log the computer off.  If i configure the tool local and set it to log off it works.  Can you tell me why it is not working via GPO?

**Comment by rkasenchak** [comment]
I created the GPO for my login but it will not log the computer off. If i configure the tool local and set it to log off it works. Can you tell me why it is not working via GPO?

**Comment by ryannewington** [comment]
Hi @rkasenchak 

If you run a resultant set of policy (rsop.msc) from the machine where you are having the problem, while logged on as the user, do you see the GPO settings applying at all?

Ryan

**Comment by rkasenchak** [comment]
@ryannewington 

when i log on as user and i run the rsop.msc it tell me i don't have access to run as the user because of admin privilege's. 

Roy

**Comment by ryannewington** [comment]
Is there anything in either of the following registry keys?

`HKLM\Software\Policies\Lithnet\IdleLogOff`
`HKCU\Software\Policies\Lithnet\IdleLogOff`

**Comment by rkasenchak** [comment]
@ryannewington 

No there is not.

**Comment by ryannewington** [comment]
That tells us the that group policy isn't applying at all to the machine or user. Double check the policy, any security filtering that may be in place, and what ou it is linked to.

**Comment by rkasenchak** [comment]
[Lithnet Logoff.docx](https://github.com/lithnet/idle-logoff/files/5881029/Lithnet.Logoff.docx)
@ryannewington  i attached screen prints of how it is setup in my group policy.  i don't see why it is not applying, do you?

**Comment by rkasenchak** [comment]
@ryannewington 

i got it to work.  thank you for all your help.

**Comment by ryannewington** [comment]
Great work! Glad you found the problem.

**Comment by rkasenchak** [comment]
@ryannewington  thank you again for all your help.
