### ISSUE TITLE
Logoff if Screensaver is instituted

### ISSUE THREAD

**Issue by rkasenchak** [lithnet/idle-logoff#29]
@ryannewington if we decided to enable the screen saver to display after 5min of inactivity and have the idle-logoff slated to log off after 30minutes will it log off or will it not see the computer Idle because of the screen saver?

**Comment by ryannewington** [comment]
Idle is based on mouse and keyboard input, so it will be fine to use screensaver.

Note that if you use the option to lock the workstation on screensaver, you may need to use the force logoff option in the GPO for idle logoff to work.
