### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by cjecwest** [lithnet/idle-logoff#3]
I have a Windows 7 machine w/ .NET 4.7 I am testing this on.  When the idle timeout comes, a .net error occurs:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lithnet.idlelogoff.Settings.get_Debug()
   at Lithnet.idlelogoff.Program.EventTimer_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Any insight would be greatly appreciated - thanks!

**Comment by ryannewington** [comment]
@cjecwest apologies for this one, and thanks for reporting it. It should be fixed in this build

https://github.com/lithnet/idle-logoff/releases/tag/v1.1.6439

Let me know if this fixes it for you or if there are still issues

**Comment by cjecwest** [comment]
This works great on the win 7! Trying to deploy via GPO to win 10 and now see this error in the event log: The assignment of application Lithnet Idle Logoff Utility from policy AutoLogOff failed.  The error was : %%1274**** .  I Can manually install the MSI fine rom the same network share.  Strange, the PCs are in the same OU.  Anyways, thank you!

**Comment by cjecwest** [comment]
This seems to do do the trick: https://serverfault.com/questions/44257/group-policy-installation-failed-error-1274
Thanks again!
