### ISSUE TITLE
desktop icons reorder themselfs after idle logoff

### ISSUE THREAD

**Issue by btowe** [lithnet/idle-logoff#32]
I'm seeing on a few computers where the desktop icon layout gets lost when the idle logoff happens.
unsure how to test this since we don't see it on normal logout or reboot.

**Comment by ryannewington** [comment]
I'm not sure what to say about this one. All we do is call the same windows API that gets called if you press the logout button in the start menu. The only difference is we set a "force" flag which prevents the "these apps are preventing you from logging off" message you normally see when they hang at logoff.

There must be some other element in play here. Something that's not shutting down gracefully when windows tells it to. 

I'd be looking for issues in the event log to do with the windows shell (explorer.exe) that might explain what's going on. It could be an explorer extension that's not unloading correctly or a corruption of the icon cache of some sort.
