### ISSUE TITLE
"The system cannot find the file specified" when viewing group policy editor AD templates

### ISSUE THREAD

**Issue by thesmj** [lithnet/idle-logoff#33]
Maybe I'm missing something, but I've been unable to get the ADMX templates to work. My install process was:

1. Install the .msi on one of our Server 2016 DCs.
2. Copy the admx file to the central store.
3. Create a new GPO, and edit it.
4. I get errors for missing files in both the lithnet.admx and lithnet.idlelogoff.admx files, and no configuration options for IdleLogoff 
are visible.

I have verified the MSI is indeed installed (The executable is installed and can be run from C:\Program Files (x86)\Lithnet) and tried rebooting the DC. I still get these errors.

**Comment by thibbs5** [comment]
did you copy the adml file as well?

**Comment by thesmj** [comment]
No, but I did now and it works!

My bad...
