### ISSUE TITLE
It doesn't work on DC

### ISSUE THREAD

**Issue by diegoal1412** [lithnet/idle-logoff#34]
Hello,

When i installed the installer on a local workstation, it's ok !

Now, i'm trying to install it on some workstations by GPO but it doesn't work.

The GPO is configured. On the machine, i see the registry key : 

Ordinateur\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Lithnet\IdleLogoff

![image](https://user-images.githubusercontent.com/50771448/127640842-9c8cf9ef-2eab-4519-a9b2-c81209efffd2.png)

It doesn't work... have you an idea ?

Thank's a lot.

Diego

**Comment by ryannewington** [comment]
Hi @diegoal1412 

How are you distributing the MSI to the workstations?

**Comment by diegoal1412** [comment]
Hi @ryannewington 

I don't distributing the MSI to the workstations, i have just configured the GPO on the DC.

I don't understand, the registry key are apply on the workstation so where is the problem ?

Thank's in advance.

Diego

**Comment by ryannewington** [comment]
You need to deploy the MSI to every workstation. 

The MSI contains the application that manages the logoff. The GPO is just registry keys - without the application to read and enforce them nothing happens.

**Comment by diegoal1412** [comment]
Thank you for your help.

It works. It's great !
