### ISSUE TITLE
GPO doesn't appear on DC after installation/reboot?

### ISSUE THREAD

**Issue by myst3r10us-str4ng3r** [lithnet/idle-logoff#35]
Hello,

I've installed the msi on a domain controller, but upon viewing the GPO editor I do not see Lithnet under Computer Configuration > Administrative Templates. I do see policies under %SystemRoot%\PolicyDefinitions\

Any input as to what might be going wrong? Thanks for any help.

![image](https://user-images.githubusercontent.com/90720932/133315101-701715a1-7f28-4283-a6b8-e1fb4207accf.png)

**Comment by ryannewington** [comment]
You may need to copy the ADMX and ADML files to your Central policy store

https://github.com/lithnet/idle-logoff/wiki/Group-policy-based-configuration

**Comment by myst3r10us-str4ng3r** [comment]
> 
> 
> You may need to copy the ADMX and ADML files to your Central policy store
> 
> https://github.com/lithnet/idle-logoff/wiki/Group-policy-based-configuration

Forgive me as sometimes Microsoft documentation is a bit opaque. I've been looking at the reference doc and from what I gather I should be copying the lithnet.admx and lithnet.idlelogoff.admx files from c:\Windows\PolicyDefinitions to C:\Windows\SYSVOL to \sysvol\domain.local\Policies\PolicyDefinitions\en-us folders, which is the existing Central Store.

After doing so I'm not seeing a change under Administrative Templates when attempting to create a new GPO. I feel like I'm missing something obvious?

**Comment by ryannewington** [comment]
Sorry for the lack of clarity, I'll get our pages updated with a bit more detail.

There are two file types you need to copy. The two ADMX files, and the two ADML files from the en-us directory.

You have the right central policy store location, but it looks like you may have placed the ADMX files in the en-us folder based on the path provided in the post.

Place the ADMXs into the PolicyDefinitions folder, and the ADMLs into the en-us sub folder.
