### ISSUE TITLE
ADMX not installed 

### ISSUE THREAD

**Issue by DavidMatthewson** [lithnet/idle-logoff#37]
Hi
I'm running W2019 servers in a Domain and have installed the *.msi file on the DC that is the base line for GPO, but I do not see the ADMX file being installed, nor can I subsequent locate it. The Wiki suggests it is auto installed at the same time as the *.msi. 

Is the ADMX available separately?

Thanks

**Comment by ryannewington** [comment]
@DavidMatthewson 

You'll need to copy the ADMX files into the central policy store for them to show up in the Group Policy editor. Instructions can be found in the [wiki](https://github.com/lithnet/idle-logoff/wiki/Group-policy-based-configuration#editing-group-policy)
