### ISSUE TITLE
Agent is not running

### ISSUE THREAD

**Issue by dimton** [lithnet/idle-logoff#38]
Hello,

I installed Idle Logoff via PDQ Deploy on a test machine.
I enabled the Group Policy setting on both Computer and User Administrative templates.
I logged off and on again.

I see no service/agent running that can handle the auto logoff action.

Can you please help? Am I missing something?

**Comment by ryannewington** [comment]
If there is nothing in task manager called `lithnet.idlelogoff.exe`, then perhaps check to see that the application actually installed correctly. It should appear in add/remove programs if it did.

**Comment by dimton** [comment]
Thanks for your response, the issue was with the Group Policy object actually, I had to point to user configuration and not both. The issue is solved.
