### ISSUE TITLE
[Feature] Notice with countdown

### ISSUE THREAD

**Issue by teknowledgist** [lithnet/idle-logoff#40]
Is there any way to add the option of a pop-up notice with a countdown of the remaining time?  That would at least give a daydreaming user the option of knowing they need to interact with the screen rather than an unceremonious logoff.  Since the application will be watching for user interaction, it wouldn't even need a button; just a touch of the mouse should close the notice and restart the (hidden) countdown.  

There would need to be two additional settings:  a "notice time" and a "message".  Thus a logoff time of 30 minutes could have a 60 second notice with the message "You are about to be logged off.  Press a key or move the mouse to remain logged in."  Making the notice "blink" (i.e. white to black to white) every 10 seconds and/or a short beep/blip would help catch a user's attention.

**Comment by dudefoxlive** [comment]
This is already a feature. If you double click the file that is in program files you can configure a message or if you are using GPO then you can configure it there.

**Comment by teknowledgist** [comment]
Ah!  I was considering using this based on the wiki which doesn't mention that in either the manual or GPO configuration pages.  I guess I should just try it instead of RTFM.  😉 

Sorry to just be making noise.

**Comment by ryannewington** [comment]
wow that's badly out of date! sorry! update incoming!

**Comment by ryannewington** [comment]
done!
