### ISSUE TITLE
How does this work with user switching

### ISSUE THREAD

**Issue by teknowledgist** [lithnet/idle-logoff#43]
Hi.  I'm trying to resolve an issue in which a locked machine (that hasn't been idle long enough to log the user out) is logged into by another user and that repeats until the machine stops responding (usually about user 3 or 4).  

Does Lithnet Idle Logoff only take action when the system is idle, or does it work at the user level?  IOW, will it log off User1 (in the background) when they have been idle while User2 is still active?

Thanks!

**Comment by ryannewington** [comment]
Each user gets their own instance of idle logoff that tracks the idle state of only that users session

**Comment by teknowledgist** [comment]
Doesn't that make it a paradox?  If an account is paused (due to user switching) then their instance of Idle Logoff isn't running, but if it somehow "wakes up" to run then the account is no longer idle.

**Comment by ryannewington** [comment]
The user session is disconnected, but still running. Nothing gets paused. Idle logoff can still independently manage the session.
________________________________
