### ISSUE TITLE
controlling the GPO from serves side ?

### ISSUE THREAD

**Issue by BKotb** [lithnet/idle-logoff#44]
i would like to add this to my domain server so i would be able to mange it at my domain, what's is the steps to to have the policy installed in the domain server ?

**Comment by ryannewington** [comment]
Hi @BKotb 

I think you are referring to a central policy store. You can find more information on how to configure this here

https://github.com/lithnet/idle-logoff/wiki/Group-policy-based-configuration#editing-group-policy
