### ISSUE TITLE
Process not starting for users

### ISSUE THREAD

**Issue by chemring-daniel** [lithnet/idle-logoff#45]
We are trialing this software on our systems, and after installing successfully (and configuring locally or via GPO) and rebooting, we are not seeing the process start.

How does the process get initiated when a user logs in? I suspect a security setting on our systems is preventing the process from starting, but not sure where to start looking to troubleshoot.

**Comment by ryannewington** [comment]
Hi @chemring-daniel 

The installer will create a registry key in `HKLM\Software\Microsoft\Windows\CurrentVersion\Run` to auto launch the application for each user that logs on.

**Comment by chemring-daniel** [comment]
Hi @ryannewington,

Thanks for the pointer. Didn't find it there but found it in `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run`.
