### ISSUE TITLE
lithnet idlelogoff not working

### ISSUE THREAD

**Issue by mserjani** [lithnet/idle-logoff#48]
Hello, I installed and configured lithnet idlelogoff on a windows 10 system but it is not working. The user accounts don't logoff after a certain amount of time, I configured the .exe to logoff after 1 minute of system being idle but nothing is happening.

**Comment by ryannewington** [comment]
Hi @mserjani 

Sorry for the delay in getting back to you.

Can you see the app running after the user logs in? Check the `HKLM\Software\Microsoft\Windows\CurrentVersion\Run` registry key and make sure the idle logoff app has an entry in there.
