### ISSUE TITLE
Is not working ?

### ISSUE THREAD

**Issue by marcelofares** [lithnet/idle-logoff#49]
I have Windows server 2022 21h2 and my workstations are Windows 10 21h2

I installed this template only on my server and created a GPO for the specific OU where I wanted to test your application.
This GPO to kill idle connections is not working in my scenario. I tested both for users and for machines and it didn't work. Any tips?

Note - This one works -> Lithnet Password Protection for Active Directory

**Comment by ryannewington** [comment]
Hi @marcelofares 

Did you install the idlelog off application on this machine, and reboot before testing?

Check to make sure the auto-start registry key is present for the app in 

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`

**Comment by marcelofares** [comment]
this printscreen is just for the station but the server has the same keys as this screenshot.
<img width="1060" alt="Captura de Tela 2022-12-15 às 20 50 04" src="https://user-images.githubusercontent.com/33350931/207991070-04ee5236-490c-4c21-a295-1348febac5fa.png">

**Comment by ryannewington** [comment]
Yes the agent is what monitors for idle time and initiates the logoff. So the agent must be installed on the target machine and the group policy needs to be assigned to the user

**Comment by marcelofares** [comment]
It worked perfectly now. Thank you very much!
