### ISSUE TITLE
Settings Box

### ISSUE THREAD

**Issue by mycroft9x** [lithnet/idle-logoff#5]
Is there a command switch to get rid of the settings box that pops up after logon?

**Comment by ryannewington** [comment]
@mycroft9x just use the `/start` argument on the command line when running the app to run it in background mode.

**Comment by Snair71** [comment]
I added through group policy and set it for 30 min. Its not logging off, do I need to push the software to the pc? Also is there a way to pre configure the logoff setting before I push the software?

**Comment by ryannewington** [comment]
@Snair71 You need to deploy the MSI to the workstations to install the workstations, and apply and configure the group policy according to how you want it to behave

**Comment by Snair71** [comment]
Sorry about that!! I completely missed the install.. My bad

Thanks,

Sanjay

Aim Specialty Health
2 Westbrook Corporate Center,
Westchester, IL 60154
Office Ext: 2041
Cell: 224.240-2759
Email: Nairs@Aimspecialtyhealth.com
