### ISSUE TITLE
Launch via cmd line without invoking GUI

### ISSUE THREAD

**Issue by bstocktonvk** [lithnet/idle-logoff#51]
Hello,
First of all, great little program! We do a fair bit of management behind the scenes and would like to install and launch without the need for a restart or log off/on. When we call the exe, I think it is waiting for a response to the GUI that gets invoked. Is it possible to launch it and just let the GPO settings take effect? Thanks.

**Comment by ryannewington** [comment]
Launch it with /start command line arg

**Comment by bstocktonvk** [comment]
> Launch it with /start command line arg

That works a treat! Thank you.
Any chance there is a list of switches or that there is a similar /stop command to kill the process?

**Comment by ryannewington** [comment]
No there isn't. You'd can use `taskkill /im ` safely on it though

**Comment by bstocktonvk** [comment]
> No there isn't. You'd can use `taskkill /im ` safely on it though

Sounds good. Again, thanks for sharing this useful utility!
