### ISSUE TITLE
Intune - Upload admx and adml files

### ISSUE THREAD

**Issue by 28kehe** [lithnet/idle-logoff#52]
Hey! I am trying to use idle-logoff on our azure devices by uploading the admx and adml files and setting up a configuration profile.
lithnet.admx and adml worked fine but when I try to upload lithnet.idlelogoff.admx I get the following error.

Object reference not set to an instance of an object.

Does anyone have some advice? Thanks in advance!

**Comment by boonedoggle** [comment]
I also see this issue and I am wondering if there is a work around.

**Comment by ryannewington** [comment]
@28kehe FYI see #54 for updated ADMX files to resolve this issue
