### ISSUE TITLE
Error: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by boonedoggle** [lithnet/idle-logoff#54]
I am trying to deploy this with Microsoft Intune. I get an error when I follow the [Import custom ADMX and ADML administrative templates into Microsoft Intune instructions](https://learn.microsoft.com/en-us/mem/intune/configuration/administrative-templates-import-custom).

## Reproducible Process:
1. Login to Intune > Device > Configuration Profiles > Import ADMX
2. [Prerequisite] Import the required `windows.admx` and `windows.adml` files from `C:\Windows\PolicyDefinitions`
3. Import the `lithnet.admx` and `lithnet.adml` files. Note that this must be done first because the next file depends on this one. This is successful.
4. Import the `lithnet.idlelogoff.admx` and `lithnet.idlelogoff.adml` files. This step fails and reports the following error:

      ```
      The upload of this ADMX file has failed.
      To continue, you will need to delete this
      upload, address the action in the error
      details and try again.
       
      ADMX file: lithnet.idlelogoff.admx
      
      State: failed
      
      Last modified date: 9/22/2023
      
      Error Details: Object reference not set to an instance of an object.
      ```

This is a fairly generic error and I cannot seem to find any information as to what the issue might be. I'm happy to work on it if anybody has any clues or references on where to start debugging.

**Comment by boonedoggle** [comment]
This is has already been brought up in #52 and was also requested in #46.

**Comment by boonedoggle** [comment]
Still needed

**Comment by ryannewington** [comment]
@boonedoggle 

Apologies for the delay, I've been away on leave.

You can download this ADMX and ADML file which should resolve the import issue

https://github.com/lithnet/idle-logoff/blob/master/src/Lithnet.IdleLogoff/PolicyDefinitions/lithnet.idlelogoff.admx
https://github.com/lithnet/idle-logoff/blob/master/src/Lithnet.IdleLogoff/PolicyDefinitions/en-US/lithnet.idlelogoff.adml

**Comment by boonedoggle** [comment]
Thanks @ryannewington! I'm confirming that 7e02f61 fixes the issue.
