### ISSUE TITLE
Install not observing parameters

### ISSUE THREAD

**Issue by hroberts65616** [lithnet/idle-logoff#55]
I may be doing something wrong myself, but not sure what. I am trying to push the application to several computers.  I am running the command:  Start-Process msiexec "/i $pkg /norestart /qn" -Wait

However the application never seems to install.  Am I missing a parameter to force it to install for me?

Then with the application installed, If I copy this to the registry of each PC it should work correct?:

[HKEY_LOCAL_MACHINE\SOFTWARE\Lithnet\IdleLogOff]
"Enabled"=dword:00000001
"IdleLimit"=dword:00000005
"IgnoreDisplayRequested"=dword:00000001
"WarningEnabled"=dword:00000000
"WarningMessage"="Your session has been idle for too long, and you will be logged out in {0}"
"WarningPeriod"=dword:00000000
"WaitForInitialInput"=dword:00000000
"Action"=dword:00000000

These particular PCs are not part of a domain to use group policy, so trying to see about pushing the application, and these keys to get it to work.

Thoughts on what I am doing?

**Comment by ryannewington** [comment]
@hroberts65616 

Is the start-process command just exiting, or is the installer hanging?

If you run the installer by hand, are there any errors presented by the installer?

**Comment by hroberts65616** [comment]
The installer hangs.  When ran manually it works without issue.  I
downloaded the file a couple of times thinking I may have had a bad copy.
It never completed.  I did find it on chocolaty and pushed it via this, and
then made the registry changes to hklm:policies/lithnet and it is working

**Comment by ryannewington** [comment]
Hm not sure what is going on there. Happy to keep troubleshooting if you need assistance, but if you are happy with your current installation method, we can leave it there.
