### ISSUE TITLE
Shutdown from Login UI

### ISSUE THREAD

**Issue by eprowe** [lithnet/idle-logoff#56]
Not sure if this is by design; however, if a workstation is waiting at the login UI it will continue to idle waiting for a user and never shutdown/restart.  Is it possible to enable an option that if the workstation is at the login screen and idea for the specified period of time the machine will take the listed action, or in the alternative, shutdown?

**Comment by ryannewington** [comment]
Hi @eprowe 

Sorry for the delay in response.

The agent runs within the user session, so with no one logged in at the log on screen, the agent isn't running at that point to be able to take action.

This is a limitation of the current design.

You could use something like a scheduled task to cover the scenario where you want to shutdown when no user is logged on. https://www.makeuseof.com/windows-10-11-shutdown-idle/
