### ISSUE TITLE
Logoff at Lockout

### ISSUE THREAD

**Issue by symptech** [lithnet/idle-logoff#6]
Idle-Logoff works fine as long as session doesn't go to lock screen first. Is there anyway to get this to work at lock screen?

**Comment by ryannewington** [comment]
@boer025 @symptech  It should handle locked sessions without any problems. Are there any errors in the event log from event source "Lithnet.idlelogoff" at the time you expect the user to be logged out?

**Comment by ryannewington** [comment]
Closing inactive ticket
