### ISSUE TITLE
ADMX not pushing correct config via GPO

### ISSUE THREAD

**Issue by ryanrowlen** [lithnet/idle-logoff#61]
We are implementing via Group Policy. I have successfully pushed the GPO to a test server. It works.

However, It seems the ADMX files are for version 1.0 and not the latest Lithnet MSI, I'm guessing this is our issue.

We have it set on our Domain Controller as 30min Idle - Logoff. No prompt to end user.

On the Test server, when we look at the settings, its set to 1 minute and says this is managed by GPO.

I have edited the ADMX file and added defaultValue "30". This ADMX is placed in our \\YourDomain\SYSVOL\YourDomain\Policies\PolicyDefinitions

I have even re-saved the settings, pulled the local ADMX, copied it over to SYSVOL\x\x\x\x. Forced a GPupdate on the test server. But still, it is set to 1 min idle logoff.

Am I missing something? Should the ADMX versions match the msi version? We're so close!!
![Screenshot 2024-09-26 161222](https://github.com/user-attachments/assets/9349e708-c9b9-483c-9036-54748da87d88)
![image](https://github.com/user-attachments/assets/2de35ad1-cbcb-4510-9dda-4d2408658d8e)
![image](https://github.com/user-attachments/assets/25b88831-5628-4453-b729-7fef828d3760)

**Comment by ryannewington** [comment]
Hi @ryanrowlen 

The ADMX files are only for you to edit the policies, if you are seeing the settings available in GPO editor then they are working correctly. They are not used in policy processing at all.

There is only one version for the ADMX files so you are using the correct ones.

I'm having a little bit of trouble understanding which bit isn't working? It's working on the test server, but not the domain controller?

The policy sets the following reg keys, so we can look at those to see if its applying correctly
computer-targeted policy
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Lithnet\IdleLogoff

user-targeted policy
HKEY_CURRENT_USER\SOFTWARE\Policies\Lithnet\IdleLogoff

**Comment by ryanrowlen** [comment]
The issue as it stands,  is that we want all of our servers to sign users off after 30 minutes. The settings were set to 30 minutes on the DC Lithnet app. Moved the ADMX files over. Now I'm beginning to think we need to edit the ADMX idlelogoff based on what you provided

We added our Print Server to the GPO to test and although it does sign the user off...it's doing it after 1 minute.

We just checked the Computer Targeted regkey on the Print Server(Test) and it is set to 1. 

Can you please help explain where in this ADMX file we can edit it to 30min for sign out?

This is the value set for the time out:
<decimal id="txt_idle_limit" key="Software\Policies\Lithnet\IdleLogoff" valueName="IdleLimit" minValue="1" />

I added this hoping it would resolve the issue:
<decimal id="txt_idle_limit" key="Software\Policies\Lithnet\IdleLogoff" valueName="IdleLimit" minValue="1" defaultValue="30"/>

Is there a better way to change the ADMX to set it to 30min before timeout?

**Comment by ryanrowlen** [comment]
![Screenshot 2024-10-02 155152](https://github.com/user-attachments/assets/2e0f7948-20ae-458d-9116-5c3ffb313795)
![Screenshot 2024-10-02 155129](https://github.com/user-attachments/assets/a0f0694e-dab4-4a16-b17e-2ebe011425f7)
![Screenshot 2024-10-02 155055](https://github.com/user-attachments/assets/13bd5ef3-6c83-4ec1-8426-bb2c79fa0de4)

**Comment by ryanrowlen** [comment]
We have tried all 3 ways but the Test Server still is overridden and set to 1min timeout.

Honestly, just need to figure out where/how to change that IdleLimit in this ADMX file. We're going crazy over here haha

**Comment by ryannewington** [comment]
hi @ryanrowlen 

You don't ever edit ADMX files. They aren't the policy, they just tell Windows how to render the screen and settings in the group policy editor. Replace the files you edited with the default files from the installation package.

From this image you sent, the GPO you've configured is setting it to 1 minute. You need to right click, edit, that group policy object in the Group Policy Management tool, Navigate to the "Logoff inactive users" setting shown in the screen shot, right click to edit that setting, and you can change the time from there to 30 mins.
![371317414-9349e708-c9b9-483c-9036-54748da87d88](https://github.com/user-attachments/assets/454d55f2-3b2d-4603-a59c-1684a8db9d56)

![image](https://github.com/user-attachments/assets/c0be7c0a-e698-4ad1-9eea-f61cf69f5477)
