### ISSUE TITLE
lithnet logoff not working

### ISSUE THREAD

**Issue by mrwizardtx** [lithnet/idle-logoff#64]
I am some what ignorant, with Github, but looking for some guidance. I see where it's loaded in registry, but not sure why it's not triggering. I can't find it in Rsop.msc. However, I don't know where I'm looking.
![lithreg](https://github.com/user-attachments/assets/dd441f6c-a739-47da-b4ff-e4c126997b5e)
thanks

**Comment by ryannewington** [comment]
@mrwizardtx The agent needs to be installed on all devices, as well as the group policy pushed out. The agent will set itself to autorun on each login, and look for the policy settings as to what to do.

**Comment by mrwizardtx** [comment]
Oh, thought it was gpo only. Thx
