### ISSUE TITLE
Disable windows event logging

### ISSUE THREAD

**Issue by VM-Master** [lithnet/idle-logoff#65]
Hi Team,

is it possible to disable event logging about logon/logoff events? 
It's a little bit complicated with german data privacy law to have such information.

![Lithnet](https://github.com/user-attachments/assets/aaae4394-88b3-4494-981c-ac7877bb19c7)

**Comment by ryannewington** [comment]
Hi @VM-Master 

There's nothing in the tool that would prevent that today. What's the problematic information? The username?

**Comment by VM-Master** [comment]
Hi @ryannewington,

We have in germany a every strict data protection. It's incomparable to the U.S.
Maybe you heard about GDPR (General Data Protection Regulation)? We do a lot to avoid any kind of tracking, CEIP, etc... 

But regarding your question. Problem is the username which identified a real employee.
With this information I can "surveil" if someone is working on a PC or not. Everyone on this PC can open the application logs and see all past events of idle logoff. 
I know as a system administrator there are many more possibility to surveil an employee.
If we could hide this information it would calm our staff council.
