### ISSUE TITLE
Pre configure the logoff minutes

### ISSUE THREAD

**Issue by Snair71** [lithnet/idle-logoff#7]
Hello I was wondering if its possible to pre-configure the minutes to like 30 min and enable it? I am using Altiris to deploy it our pc's. I tried the group policy config but it doesn't do anything.

**Comment by ryannewington** [comment]
@Snair71 I'm not sure what you mean here. If nothing happened, either the GPO hasn't applied, or the MSI did not install correctly.

You will need to logoff and log back on after installing the MSI for the agent to be loaded into your session.
