### ISSUE TITLE
Trying to use GPO for this

### ISSUE THREAD

**Issue by theotherguy2175** [lithnet/idle-logoff#8]
Ok im extremely confused on the instructions. You say to push this with policy you have you simply enable the setting in GPO. Though it doesn't appear in the GPO editor. Which i thought you then meant to install the MSI on the Domain Controller, but that also didnt make the Template appear in GPO. What am i doing wrong? 

Thanks.

**Comment by theotherguy2175** [comment]
I was able to figure this out. Basically i had to install it to my machine, then move the admx file from my machine to the sysvol/profile folder. Thanks. Really amazing tool, going to make our lab environment much easier to manage.

**Comment by ryannewington** [comment]
Thanks for the feedback @theotherguy2175. I've updated the wiki page to make this a bit clearer.
